### PR TITLE
Initialize saveDev with an array - attempted fix for bug caused by trying to call concat on undefined

### PR DESCRIPTION
**Pull request by jbgarr**

### CODE REVIEW

**Comment by AlexYegupov** [comment]
Problem seems exists. When yarn is present in system then cannot command 
`create-react-app my-app --scripts-version cc-react-scripts`
is failed:

Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: Cannot read property 'concat' of undefined
    at module.exports (/tmp/my-app2/node_modules/cc-react-scripts/scripts/init.js:144:23)
    at getPackageName.then.then.then.packageName (/usr/lib/node_modules/create-react-app/createReactApp.js:306:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

As seems in code problem is in the unitialized saveDev variable in case of useYarn is true.

**Comment by Frankcarvajal** [comment]
This deletes the package.json as well, which prevents the ability to run locally.

screen shot 2018-01-09 at 8 38 16 pm

**Comment by jordanpapaleo** [comment]
Merged. I do not have yarn.  Anyone with yarn want to give it a try? @jbgarr

**Comment by jbgarr** [comment]
I was able to test it out and unfortunately the update didn't fix it. I'll have to dig in again when I have more time. Is there a way to run/test a local version of the code or does it always run the freshly downloaded version?

**Comment by jordanpapaleo** [comment]
@jonlu What was your process for local testing?

**Pull request merged**
